name: davidlyness.com
description: Thoughts go in, words come out.
url: https://davidlyness.com
google_analytics_id: UA-78184939-1

paginate: 5
permalink: :title

sass:
  style: :compressed

author:
  name: David Lyness
  email: david@lyness.io
  twitter: davidlyness

twitter:
  username: davidlyness

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

theme: jekyll-theme-slate
